from collections import deque
from typing import (Callable, Collection, Iterable, MutableSequence, Sequence,
                    Sized, SupportsIndex, overload)

from pytableaux.typing import _VT, _MSeqT, _SeqT

EMPTY_SEQ: seqf

def absindex(seqlen: int, index: SupportsIndex, strict: bool = ...) -> int: ...
def slicerange(seqlen: int, slice_: slice, values: Sized, strict: bool = ...) -> range: ...

class SequenceApi(Sequence[_VT]):
    @overload
    def __getitem__(self, i: SupportsIndex) -> _VT: ...
    @overload
    def __getitem__(self:_SeqT, s: slice) -> _SeqT: ...
    @overload
    def __delitem__(self, i: SupportsIndex)->None: ...
    @overload
    def __delitem__(self, i: slice)->None: ...
    @overload
    def __setitem__(self, i: SupportsIndex, value: _VT)->None: ...
    @overload
    def __setitem__(self, i: slice, value: Collection)->None: ...
    def __mul__(self:_SeqT, other: SupportsIndex) -> _SeqT: ...
    def __rmul__(self:_SeqT, other: SupportsIndex) -> _SeqT: ...
    def __add__(self:_SeqT, other: Iterable) -> _SeqT: ...
    def __radd__(self:_SeqT, other: Iterable) -> _SeqT: ...
    @classmethod
    def _from_iterable(cls: type[_SeqT], it: Iterable) -> _SeqT:...
    @classmethod
    def _concat_res_type(cls, othrtype: type[Iterable], /) -> type[SequenceApi]: ...
    @classmethod
    def _rconcat_res_type(cls, othrtype: type[Iterable], /) -> type[SequenceApi]: ...

class MutableSequenceApi(SequenceApi[_VT], MutableSequence[_VT]):
    def sort(self, *, key: Callable | None = ..., reverse: bool = ...) -> None: ...
    def __imul__(self:_MSeqT, other: SupportsIndex) -> _MSeqT: ...

class seqf(tuple[_VT, ...], SequenceApi[_VT]):
    @overload
    def __radd__(self, other: tuple[_VT, ...]) -> tuple[_VT, ...]: ...
    @overload
    def __radd__(self, other: list[_VT]) -> list[_VT]: ...
    @overload
    def __radd__(self, other: deque[_VT]) -> deque[_VT]: ...
    @overload
    def __radd__(self, other: seqf[_VT]) -> seqf[_VT]: ...

class SeqCover(SequenceApi[_VT]): ...
class seqm(MutableSequenceApi[_VT],list[_VT]): ...
class deqseq(MutableSequenceApi[_VT],deque[_VT]): ...
