class Events(object):
    AFTER_APPLY        = 10
    AFTER_BRANCH_ADD   = 20
    AFTER_BRANCH_CLOSE = 30
    AFTER_NODE_ADD     = 40
    AFTER_NODE_TICK    = 50
    AFTER_RULE_APPLY   = 60
    AFTER_TRUNK_BUILD  = 70
    BEFORE_TRUNK_BUILD = 100